### ISSUE TITLE
More than 10% of messages are being held back

### ISSUE THREAD

**Issue by henare** [openaustralia/cuttlefish#3]
Extracted from upstream https://github.com/mlandauer/cuttlefish/issues/235:

>henare commented on 22 Feb 2016 
>This week 7,071 messages were held back out of a total of 72,033. Is that a lot or to be expected?

**Comment by mlandauer** [comment]
This would be fixed by fixing https://github.com/mlandauer/cuttlefish/issues/121. So, closing this issue in favour of that one
