### ISSUE TITLE
Let me know when emails to a specific address start bouncing

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/cuttlefish#7]
We have some important addresses that we really don't want emails to bounce off—our address for abuse reports, and the addresses of local councils and councilors.

I don't know enough about why emails bounce to know if we can just solve the problem of them ever bouncing—but, barring that, it would be good to know when emails to these addresses start bouncing so that we can fix the situation immediately.

Possible solutions:

* email to our team
* slack notification

**Comment by mlandauer** [comment]
I think the solution to this problem would be a combination of [web hooks for delivery failures and success](https://github.com/mlandauer/cuttlefish/issues/27) and [clearing out blacklist entries after a certain amount of time](https://github.com/mlandauer/cuttlefish/issues/121). This would be a more general solution. So, closing this issue in favour of those two
